---
title: "Genome assemblies evaluation"
author: "Natalia Zajac"
date: "07/09/2025"
output:
  html_document: 
    highlight: pygments
    theme: sand
    code_folding: hide
    toc: yes
    toc_depth: 4
editor_options: 
  chunk_output_type: inline
---


```{r include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 8, fig.height = 8, warning = FALSE, error = FALSE, cache = FALSE
)
```

# {.tabset}

## BUSCO {.tabset}

### NUC

```{r, echo=FALSE, message=FALSE}

library(utils)
library(dplyr)
library(tidyverse)
library(rentrez)
library(xml2)
library(ape)
library(ggtree)
library(dplyr)
library(tidyverse)
library(ggstar)
library(cowplot)
library(patchwork)
library(ggnewscale)
library(tidytree)
library(ezRun)

busco_files = list.files("/groups/mpistaff/Zajac/analyses/BUSCO/", pattern = "short_summary.specific.squamata_odb12", recursive = TRUE)[!grepl("sexchr", list.files("/groups/mpistaff/Zajac/analyses/BUSCO/", pattern = "short_summary.specific.squamata_odb12", recursive = TRUE))]
busco_files = busco_files[grepl(".txt", busco_files)]

busco_results = NULL
for (i in busco_files){
  name = str_remove(sapply(str_split(i, "/"), .subset ,1), ".fasta")
  line8 <- readLines(paste0("/groups/mpistaff/Zajac/analyses/BUSCO/",i), n = 9)[9]
  line8 = data.frame(str_split(sapply(str_split(line8, "\t"), .subset, 2), ","))
  colnames(line8) = name
  line8[[1]] = sapply(str_split(line8[[1]], ":"), .subset, 2)
  line8[[1]] = as.numeric(str_remove(str_remove(str_remove(line8[[1]], "%"), "\\[S"), "\\]"))
  rownames(line8) = c("Complete", "Duplicated", "Framgented", "Missing", "n", "E")
  if (is.null(busco_results) == TRUE){
    busco_results = line8
  } else {
    busco_results = cbind(busco_results, line8)
  }
}

single = busco_results[1,] - busco_results[2,]
busco_results <- rbind(busco_results, single)
rownames(busco_results)[nrow(busco_results)] <- "Single"
```


```{r, fig.height=15, fig.width=20}
p1 = busco_results[c(-1,-5,-6),] %>% rownames_to_column() %>% reshape2::melt(id.vars = "rowname") %>% mutate(variable = sapply(str_split(variable, "Busco_"), .subset ,2)) %>% ggplot(aes(variable, value)) + geom_col() + facet_wrap(~rowname, scales = "free") + theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust=1))
p1

pdf("../Figures/Choosing_cretensis_BUSCO.pdf", height = 6, width = 10)
p1
dev.off()
```

### PROT. 
 
```{r, echo=FALSE, message=FALSE}
    
busco_files = list.files("/groups/mpistaff/Zajac/proteomes/data/ALL_Tiberius_annotated/OMARK/", pattern = ".sum$", recursive = TRUE)
busco_files = busco_files[!grepl("NoZW", busco_files)]

busco_results2 = NULL
for (i in busco_files){
  name = str_remove(sapply(str_split(i, "/"), .subset ,1), ".sum")
  line8 <- readLines(paste0("/groups/mpistaff/Zajac/proteomes/data/ALL_Tiberius_annotated/OMARK/",i), n = 9)[6]
  line8 = data.frame(Result = str_remove(str_remove(sapply(str_split(line8, ","), .subset, 1), "S:"), "%")) %>% mutate(Genome= name)
  if (is.null(busco_results2) == TRUE){
    busco_results2 = line8
  } else {
    busco_results2 = rbind(busco_results2, line8)
  }
}

busco_results2[busco_results2$Genome == "PodMur1",]$Genome = "PodMur1#1"

p1 = busco_results2 %>% ggplot(aes(Genome, Result)) + geom_point()

p1 #Only Single
```

```{r, echo=FALSE, message=FALSE}
    
## This chunck just loads the amount of protein coding sequence per genome for downstream analyses

sizes = NULL
for (i in list.files("../chromosome_sets/", patter = "fai", recursive = T)[grep("unmasked/community", list.files("../chromosome_sets/", patter = "fai", recursive = T))]){
  xxx = read.delim(paste0("../chromosome_sets/",i), header = F)[,c(1,2)] %>% separate(V1, into = c("species", "haplotype", "chromosome"),sep = "#") %>% mutate(genome = paste0(species,"#", haplotype))
  sizes = rbind(sizes, xxx)
}
sizes = sizes %>% group_by(genome) %>% summarise("Total.length" = sum(V2)) 

all_gffs = NULL
for (i in list.files("/groups/mpistaff/Zajac/proteomes/data/ALL_Tiberius_annotated/", pattern = ".gtf")){
  gff = readGFF(paste0("/groups/mpistaff/Zajac/proteomes/data/ALL_Tiberius_annotated/", i))
  gff = gff[gff$type == "CDS",] %>% data.frame() %>% mutate(length = end - start) %>% group_by(group) %>% summarise(length = sum(length)) 
  gff = data.frame(genome = i, prot_coding_seq = sum(gff$length))
  all_gffs = rbind(gff, all_gffs)
}

podmur = readGFF("/groups/mpistaff/Zajac/proteomes/data/GCF_004329235.1/genomic.gff")
podmur = podmur[podmur$seqid %in% unique(podmur$seqid)[grep("NC", unique(podmur$seqid))][-20],]
podmur = podmur[podmur$type == "CDS",] %>% data.frame() %>% mutate(length = end - start) %>% group_by(ID, gene) %>% summarise(length = sum(length)) %>% group_by(gene) %>% summarise(length = mean(length)) 
all_gffs = rbind(all_gffs, data.frame(genome = "PodMur1#1",prot_coding_seq = sum(podmur$length)))

raf = readGFF("/groups/mpistaff/Zajac/proteomes/data/GCF_027172205.1/genomic.gff")
raf = raf[raf$seqid %in% unique(raf$seqid)[grep("NC", unique(raf$seqid))],]
raf = raf[raf$type == "CDS",] %>% data.frame() %>% mutate(length = end - start) %>% group_by(ID, gene) %>% summarise(length = sum(length)) %>% group_by(gene) %>% summarise(length = mean(length)) 
all_gffs = rbind(all_gffs, data.frame(genome = "rPodRaf1#1", prot_coding_seq = sum(raf$length)))

all_gffs$genome = str_remove(all_gffs$genome,".gtf")
all_gffs = merge(sizes, all_gffs, by = "genome") %>% mutate(perc_prot = (prot_coding_seq*100)/Total.length)
```

## QUAST

```{r, fig.height=10, fig.width=10}

quast = NULL
for (i in list.files("/groups/mpistaff/Zajac/analyses/quast_results_20chr/", pattern = "transposed_report.tsv", recursive = T)){
  df = ezRead.table(file.path("/groups/mpistaff/Zajac/analyses/quast_results_20chr/", i))
  quast = rbind(df, quast)
}
quast = quast[-1,]

quast[,c(14,15,16,17,18,21)] %>% rownames_to_column() %>% reshape2::melt(id.vars = "rowname") %>% ggplot(aes(rowname, value)) + geom_point() + facet_wrap(~variable, scales = "free", ncol = 2) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

pdf("../Figures/Choosing_cretensis_QUAST.pdf", height = 10, width = 10)
quast[,c(14,15,16,17,18,21)] %>% rownames_to_column() %>% reshape2::melt(id.vars = "rowname") %>% mutate(rowname = str_remove(str_replace(rowname, "_", "#"), ".all")) %>% mutate(rowname = if_else(grepl("#", rowname), rowname, paste0(rowname, "#1"))) %>% arrange(rowname) %>% ggplot(aes(rowname, value)) + geom_point() + facet_wrap(~variable, scales = "free", ncol = 2) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
dev.off()

```

## GC content.  

```{r, echo=FALSE, message=FALSE, fig.height=25, fig.width=25}
plots = NULL
all_gcns = NULL
for (i in list.files("/groups/mpistaff/Zajac/analyses/GCN_content/", pattern = "GCN_CONTENT")[-1]){
  bedfile = paste0("/groups/mpistaff/Zajac/genomes/ncbi_dataset/data/ALL_corrected_masked/", gsub(".GCN_CONTENT_200k.bedtools_nuc.bed", "", i), ".fasta.fai")
  bed = read.delim(bedfile, header = F)[,c(1,2)]
  colnames(bed) = c("Chr", "length")
  chromosomes = bed %>% arrange(length) %>% dplyr::select(Chr) %>% as.list()
  bed$Chr = factor(bed$Chr, levels = chromosomes$Chr)
  gcn = read.delim(paste0("/groups/mpistaff/Zajac/analyses/GCN_content/" , i), header = F)
  colnames(gcn) = c("Chr", "Start", "End", "GC", "N")
  gcn$Chr = factor(gcn$Chr, levels = levels(bed$Chr))
  p1 = ggplot() +
      geom_segment(data = bed,
                   aes(x = 0, xend = length,
                       y = Chr, yend = Chr),
                   size = 4, color = "grey80") +
      # Add inversions as colored rectangles
      geom_rect(data = gcn,
                aes(xmin = Start, xmax = End,
                    ymin = as.numeric(factor(Chr)) - 0.3,
                    ymax = as.numeric(factor(Chr)) + 0.3,
                    fill = GC)) +
      labs(x = "Position (bp)", y = "Chromosome",
           title = "GC content") +
      theme_minimal() + scale_fill_viridis_b(limits = c(35, 65))
  all_gcns = rbind(gcn,all_gcns)
  plots[[i]] = p1
}


plot_grid(plotlist = plots, ncol = 5)


all_gcns$species = sapply(str_split(all_gcns$Chr, "#"), .subset, 1)
all_gcns %>% ggplot(aes(GC, colour = species)) + geom_density()
```

## Summary tree

```{r annotate, include=FALSE}

##Additional thins to put in kmer similarity between haplotypes, level of synteny between haplotypes

tree = "/groups/mpistaff/Zajac/genomes/mashtree.bootstrap.haplotypes.nwk"
tree = treeio::read.tree(tree)
df = read_delim("/groups/mpistaff/Zajac/genomes/sample_data.tsv")
df$clade = factor(df$clade, levels = c("Iberian", "Muralis", "Siculus", "Balkan", "Sicilian-Maltese", "Western"))
df = rbind(df[,c(3,16,17)] %>% mutate(MyName = paste0(MyName, "#1")), df[,c(3,16,17)] %>% mutate(MyName = paste0(MyName, "#2"))) %>% filter(!MyName %in% c("PodMur1#2", "rPodRaf1#2", "rPodCre2.1#2", "rPodLil1.2#2", "Pmuni1.1#1", "Pmuni1.1#2")) %>% unique() 
busco = reshape2::melt(busco_results[c(-1,-5,-6),] %>% rownames_to_column()) %>% 
    filter(rowname == "Single") %>% mutate(variable = str_replace(variable,"Busco_", "")) 
busco = busco %>% mutate(haplotype = sapply(str_split(variable, "#"), .subset, 2))
genes = read.delim("../GeneSpace2/bed/nb_genes.txt", header = FALSE)

#Similarity between haplotypes
pankmer = read.delim("../PanKmer/genomes_adj_matrix.csv", check.names = FALSE, sep = ",")
colnames(pankmer) = c("Name", str_remove(colnames(pankmer)[2:27], ".all"))
pankmer$Name = str_remove(pankmer$Name, ".all")
pankmer = pankmer %>% column_to_rownames("Name")
pankmer = as.matrix(pankmer)
pankmer <- as.matrix(pankmer) * 1   
mode(pankmer) <- "numeric"
k <- 31
eps <- 1e-12
genome_kmers <- diag(pankmer) 
# Jaccard
J <- matrix(NA, nrow(pankmer), ncol(pankmer), dimnames=dimnames(pankmer))
for (i in 1:nrow(pankmer)) {
  for (j in 1:ncol(pankmer)) {
    shared <- pankmer[i, j]
    union  <- genome_kmers[i] + genome_kmers[j] - shared
    if (union > 0) {
      J[i, j] <- shared / union
    } else {
      J[i, j] <- NA
    }
  }
}
J <- pmin(pmax(J, eps), 1 - eps, na.rm=TRUE)
#ANI
d   <- -(1/k) * log((2*J)/(1+J))
ani <- 1 - d
diag(ani) <- 1
ani[ani < 0] <- 0
ani[ani > 1] <- 1
ani = ani %>% ezFrame() %>% rownames_to_column() %>% reshape2::melt(id.vars = "rowname")
ani = ani %>% filter(sapply(str_split(rowname, "#"), .subset, 1) == sapply(str_split(variable, "#"), .subset, 1)) %>% filter(rowname != variable)

#Synteny between haplotypes
all_syns = NULL
for (i in list.files("../SYRI/", pattern = ".summary", recursive = TRUE)){
  name1 = sapply(str_split(str_remove(sapply(str_split(i , "/"), .subset, 2), "syri.summary"), "_"), .subset, 1)
  name2 = sapply(str_split(str_remove(sapply(str_split(i , "/"), .subset, 2), "syri.summary"), "_"), .subset, 2)
  df = readLines(paste0("../SYRI/",i))[3]
  df = data.frame(str_split(df, "\t"))[c(-1, -2), , drop = FALSE] 
  colnames(df) = c("Results")
  df = df %>% mutate("Hap" = c(name1, name2))
  all_syns = rbind(all_syns,df)
}
sizes = NULL
for (i in list.files("../chromosome_sets/", patter = "fai", recursive = T)[grep("unmasked/community", list.files("../chromosome_sets/", patter = "fai", recursive = T))]){
  xxx = read.delim(paste0("../chromosome_sets/",i), header = F)[,c(1,2)]
  sizes = rbind(sizes, xxx)
}
all_syns = merge(all_syns, sizes, by.x = "Hap", by.y = "V1")
all_syns = all_syns %>% separate(Hap, into = c("species", "haplotype", "chromosome"),sep = "#") %>% mutate(genome = paste0(species,"#", haplotype)) %>% group_by(genome) %>% mutate(synteny = sum(as.numeric(Results)) * 100 / sum(V2)) %>% dplyr::select(6,7) %>% unique()


p1 = ggtree(tree) +
    geom_tiplab(size = 3) + 
    xlim_expand(c(0,0.05), panel = "Tree")

p1 = p1 %<+% merge(p1$data, df, by.x = "label", by.y = "MyName") + geom_tippoint(aes(color=clade)) + scale_color_manual(values = c("magenta2", "green", "yellow", "purple", "palegreen3", "blue3", "red", "orange")) + labs(color = "Clade")

p1 + 
  new_scale_fill() +
  geom_facet(panel = "Genome Length (Gb)", data = quast %>% rownames_to_column() %>% mutate(rowname = str_remove(str_replace(rowname, "_", "#"), ".all")) %>% mutate(rowname = ifelse(grepl("#", rowname), rowname, paste0(rowname, "#1"))) %>% dplyr::select(1,8) , geom = geom_col,mapping=aes(x = `Total length (>= 0 bp)`/1000000000, y = y), orientation = 'y', width = .6,inherit.aes = FALSE) + 
  geom_facet(panel = "Scaffold N50 (Mb)", data = quast %>% rownames_to_column() %>% mutate(rowname = str_remove(str_replace(rowname, "_", "#"), ".all")) %>% mutate(rowname = ifelse(grepl("#", rowname), rowname, paste0(rowname, "#1"))) %>% dplyr::select(1,18) , geom = geom_col,mapping=aes(x = N50/1000000, y = y), orientation = 'y', width = .6,inherit.aes = FALSE) + 
  geom_facet(panel = "#Ns per 100kb", data = quast %>% rownames_to_column() %>% mutate(rowname = str_remove(str_replace(rowname, "_", "#"), ".all")) %>% mutate(rowname = ifelse(grepl("#", rowname), rowname, paste0(rowname, "#1"))) %>% dplyr::select(1,22) , geom = geom_point,mapping=aes(x = `# N's per 100 kbp`, y = y),inherit.aes = FALSE) + 
  geom_facet(panel = "BUSCO Single (%)", data = busco[,c(2,3,4)], geom = geom_point, mapping=aes(x = value, y = y, colour = haplotype),size = 3, inherit.aes = FALSE) + 
  geom_facet(panel = "GC content (%)", data = quast %>% rownames_to_column() %>% mutate(rowname = str_remove(str_replace(rowname, "_", "#"), ".all")) %>% mutate(rowname = ifelse(grepl("#", rowname), rowname, paste0(rowname, "#1"))) %>% dplyr::select(1,17) , geom = geom_point,mapping=aes(x = `GC (%)`, y = y),inherit.aes = FALSE) + 
  geom_facet(panel = "ANI between haps", data = ani %>% dplyr::select(1,3) , geom = geom_point,mapping=aes(x = round(value*100,2), y = y),  colour = "blue", inherit.aes = FALSE) + 
  geom_facet(panel = "Synteny between haps", data = all_syns , geom = geom_point,mapping=aes(x = synteny, y = y),  colour = "blue", inherit.aes = FALSE) + 
    geom_facet(panel = "Number of genes (k)", data = genes %>% mutate(haplotype = sapply(str_split(V1, "#"), .subset, 2)) , geom = geom_point,mapping=aes(x =V2/1000, y = y, colour = haplotype),size = 3, inherit.aes = FALSE) + 
  geom_facet(panel = "OMARK Single (%)", data = busco_results2 %>% dplyr::select(2,1) %>% mutate(haplotype = sapply(str_split(Genome, "#"), .subset, 2)) , geom = geom_point,mapping=aes(x =as.numeric(Result), y = y, colour = haplotype),size = 3, inherit.aes = FALSE) + 
  geom_facet(panel = "Genome Len in CDS (%)", data = all_gffs[,c(1,4)] , geom = geom_point,mapping=aes(x =as.numeric(perc_prot), y = y), xlim = c(0,5), inherit.aes = FALSE) +  
  theme_bw()

```


## MASH DISTANCES


```{r, fig.width=14, fig.height=10}

df = read_delim("/groups/mpistaff/Zajac/genomes/sample_data.tsv")
df$clade = factor(df$clade, levels = c("Iberian", "Muralis", "Siculus", "Balkan", "Sicilian-Maltese", "Western"))
mash = read.delim("/groups/mpistaff/Zajac/analyses/ntsynt/pairwise_mash_distances.txt", header = FALSE)
mash$V1 = sapply(str_split(mash$V1, ".all.fasta"), .subset, 1)
mash$V2 = sapply(str_split(mash$V2, ".all.fasta"), .subset, 1)
mash$MyName1 = sapply(str_split(mash$V1, "#"), .subset, 1)
mash$MyName2 = sapply(str_split(mash$V2, "#"), .subset, 1)

strip_colors <- c("magenta2", "green", "yellow", "purple", "palegreen3", "blue3")

p1 = merge(merge(mash, unique(df[,c(3,16,17)]), by.x = "MyName1", by.y = "MyName"), unique(df[,c(3,16,17)]), by.x = "MyName2", by.y = "MyName") %>% ggplot(aes(paste0(Organism.Name.x, "#", sapply(str_split(V1, "#"), .subset, 2)), paste0(Organism.Name.y, "#", sapply(str_split(V2, "#"), .subset, 2)), fill = V3)) + 
    geom_tile() +
    scale_fill_viridis(option = "G") +
    #geom_text(aes(label = round(V3,2)), size = 5) + 
    facet_grid2(
        clade.y ~ clade.x, 
        scales = "free", 
        space = "free", 
        switch = "x",
        strip = strip_themed(
            background_x = elem_list_rect(fill = strip_colors),  # Apply colors to x-strips
            background_y = elem_list_rect(fill = strip_colors)   # Apply colors to y-strips
        )
    ) + theme(panel.spacing.x  = unit(0, "mm"),
              panel.background = element_rect(fill = NA, color = "black", linewidth = 0.5),
              panel.grid       = element_blank(), axis.text.y = element_text(size = 15, face = "italic"), axis.text.x = element_blank(), axis.title.x = element_blank(), strip.text = element_text(size = 9)) + labs(fill = "Jaccard distance", y = "")

p2 = mash[,c(1,2,3)] %>% pivot_wider(names_from = V2, values_from = V3) %>% column_to_rownames("V1") %>% mutate(sum = rowSums(.[1:26])) %>% rownames_to_column() %>% ggplot(aes(sum, rowname)) + geom_point() + labs(y = "genome", x = "mash distances summed")

p1
```



```{r, fig.width=6, fig.height=6}
p2 

```


## Length of chromosomes

```{r, fig.height=15, fig.width=15}
all = NULL
for (i in list.files("../chromosome_sets/", pattern = "combined.fasta.fai", recursive = T)){
  df = read.delim(paste0("../chromosome_sets/",i), header = F)
  df$chromosome = sapply(str_split(df$V1, "#"), .subset, 3)
  all =  rbind(all , df)
}
all %>% ggplot(aes(V1, V2)) + geom_col() + facet_wrap(~chromosome, scales = "free") + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))

```



```{r, fig.height=7, fig.width=7}
all %>% 
    group_by(chromosome) %>%
    mutate(Rank = rank(-V2, ties.method = "first")) %>%
    ungroup() %>% mutate(genome = sapply(str_split(V1, "#"), .subset, 1), haplotype = sapply(str_split(V1, "#"), .subset, 2)) %>% ggplot(aes(paste0(genome,haplotype), Rank)) + geom_boxplot() + labs(x = "genome", y = "Score (lower the longer the chromosomes usually)") + theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

pdf("../Figures/Choosing_cretensis_CHRLEN.pdf", height = 4, width = 10)
all %>% 
    group_by(chromosome) %>%
    mutate(Rank = rank(-V2, ties.method = "first")) %>%
    ungroup() %>% mutate(genome = sapply(str_split(V1, "#"), .subset, 1), haplotype = sapply(str_split(V1, "#"), .subset, 2)) %>% ggplot(aes(paste0(genome,haplotype), Rank)) + geom_boxplot() + labs(x = "genome", y = "Score (lower the longer the chromosomes usually)") + theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
dev.off()
```